### ISSUE TITLE
Chybna konverze convertToTimePoint()

### ISSUE THREAD

**Issue by fmikulu** [logimic/RdsGatewayRepM3#13]
Mam pripojeny realny device, nebyl nastaven RTC (je tam asi neco default po startu)

GetTimeEndDate: request="b1.01.0d.0e.b2"
GetTimeEndDate: response="b1.09.0d.38.36.15.07.00.00.61.13.14.b2"

asi je chybne interpretovano, mktime vraci -1

Tipnul bych si na chybu nekde zde: _time.tm_year = yearFromCentury(data.date_year.data, data.date_century.data) - 1900;_
![000685](https://user-images.githubusercontent.com/17859927/150006153-bc989cef-3988-4db9-940a-607ab171f231.png)

**Comment by nandra** [comment]
Hmm pozrel som to a testy zlyhavaju. Data vyzeraju divne lebo 0x61 je rok a 0x13 je storocie. Cize ak sa to prevedie tak je to fakt 1897 ;).PO koverzii mi to vratilo : `Fri Jan  8 21:54:56 1897`

**Comment by fmikulu** [comment]
To může být OK, protože jak jsem psal, RTC není nastavený. Jde jen o to, aby to neselhalo a vrátilo to "správně" špatný čas. Logika nad tím pak zjistí že je to špatně a nastaví RTC. Toto musíme být schopní obsloužit, protože při odpojení (výměna) baterie se RTC zresetuje.

**Comment by nandra** [comment]
OK chapem, len sa troska divym lebo mam na toto test a vrati mi to ten cas co som pisal hore a mktime mi nevrati -1-ku. Pouzil som presne data ktore su v response. Moze by nejaky rozdiel windows/linux? Dik.

**Comment by nandra** [comment]
Uz to chapem. mktime sa rok dava ako rok -1900 a nam rok vrati 1897 cize je tam negativny rok. Idem este raz skontrolovat test :). Dik

**Comment by fmikulu** [comment]
Ano, tam si myslim je problem, obecne by to ale melo akceptovat i -rok => b.c.?

**Comment by fmikulu** [comment]
Vyreseno b6755f7fba9da5c1844af9c191f48edccdd37d03
