### ISSUE TITLE
MSVC compatibility packed struct

### ISSUE THREAD

**Issue by fmikulu** [logimic/RdsGatewayRepM3#2]
Potrebujem aby se dalo prelozit pod MSVC compilerem.

Problem je zde:
https://github.com/logimic/RdsGatewayRepM3/blob/20a289686a9fe75846575e2392d10abd81f3da53/RepM3/repM3.h#L285

Pokud je skutecne treba takto deklarovat musime to poresit pres makro, napr:
https://stackoverflow.com/questions/1537964/visual-c-equivalent-of-gccs-attribute-packed

**Comment by nandra** [comment]
Pridal som nejaku magiu z toho prispevku, uvidime ako to skompiluje msvc

**Comment by fmikulu** [comment]
ok
