### ISSUE TITLE
Nestandartni C++ typ uint

### ISSUE THREAD

**Issue by fmikulu** [logimic/RdsGatewayRepM3#3]
V C++ neni standartne definovany typ uint a nejde tedy v MSVS prelozit repM3.h
napr: https://github.com/logimic/RdsGatewayRepM3/blob/20a289686a9fe75846575e2392d10abd81f3da53/RepM3/repM3.h#L22
Zatim jsem poresil pomoci:
```cpp
typedef unsigned uint;
```
ale mel by byt pouzity standartni typ, napr: **uint32_t**

**Comment by nandra** [comment]
ok prehodil som to na uint32_t
