### ISSUE TITLE
Pouziti C++ exception

### ISSUE THREAD

**Issue by fmikulu** [logimic/RdsGatewayRepM3#4]
Pouzivejme raději vyjimky oddedene od std::exception
https://github.com/logimic/RdsGatewayRepM3/blob/20a289686a9fe75846575e2392d10abd81f3da53/RepM3/repM3.h#L193
Tak aby se informace o chybe snadno propagovala do vyssich vrstev a do logu. Neni treba deklarovat vlastni vyjimky, ale muze byt. V podstate staci std::logic_error, napr:

```cpp
        // first and last bytes must be start/stop bytes
        if (d[0] != start_byte || d[d.size()-1] != stop_byte)  {
          std::ostrinstream os;
          os << "Wrong start or stop byte: " << std::hex << unsigned(d[0]);
          std::logic_error ex(os.str().c_str());
          throw ex;
        }
```

**Comment by nandra** [comment]
OK pridam. Vdaka

**Comment by nandra** [comment]
Hotovo
