### ISSUE TITLE
rapidjson

### ISSUE THREAD

**Issue by nandra** [logimic/RdsGatewayRepM3#8]
Exituje legantne riesenie ako pridat deserializaciu json na strukturu? Serializaciu mam example pre UINT8 (aj unittest), ale pri deserializacii som nic pekne nenasiel. DIk.

**Comment by fmikulu** [comment]
Headery reapidjson potrebujem bud nakopirovat do projektu, nebo pridat jako git subrepo, tak, aby to slo prelozit po git pull.
Jak to mas poresene?

**Comment by fmikulu** [comment]
Nepotrebujeme ser/deser do detailu vse. Pokusim se ASAP doplnit do specifikace jak by mely vypadat tridy komandu a z toho vyplyne co se bude ser/deser. 
Potrebuju abstrakci od "hrani" si s bitiky a dostat vse do string, bool, number(int, double), chrono, protoze to ve vysledku pujde z/do FND (web frontend) a do cvs, pdf sestav a nepotrebuju se hrabat v bitikach. Vsechny UINT8, UINT16, ... potrebuju namapovat na int a naopak. 

Interface jsou ty komand tridy, ktere maji obecne metody :
- dej mi buffer s request k odeslani CMD do IQRF
- zpracuj buffer s response co se vratil z IQRF
- set metody nad typy string, bool, number, chrono pro request, nebo manipulacni tridy slozene z techto typu
- get metody nad typy string, bool, number, chrono pro response, nebo manipulacni tridy slozene z techto typu

Napr: 
class GetVersionCmd : public baseCmd {
private: //...

public:
  class Version {
    int fw_version_minor;
    int fw_version_major;
    int fw_pre_release_nr;
    int hw_variant;
  };
   rapidjson::Value encode() {
      using namespace rapidjson;
      Value val(Type::kObjectType);
      Pointer("/minor").Set(val, fw_version_minor, a);
      //...
      return val;
   }

   rapidjson::Value parse() {
     //nepotrebujem
     throw std::logic_error ex("unsuported");
   }
}

  Version getVersion() { return ....; } ;
};

**Comment by nandra** [comment]
> Headery reapidjson potrebujem bud nakopirovat do projektu, nebo pridat jako git subrepo, tak, aby to slo prelozit po git pull. Jak to mas poresene?

Zatial som len na kompe nainstaloval dev balicek a spolieham sa ze to najde, ale samozrejme pridat submodule s rapidjson. Dik.

**Comment by nandra** [comment]
Submodule pridany do 3rdparty

**Comment by fmikulu** [comment]
Submodule OK, nepotrebujem primo ser/deser vsech data typu, pouze casu, reportu viz. #10
